### PR TITLE
Update babel dependencies

### PR DESCRIPTION
**Pull request by megawac**
Going to be opening several pulls based off changes I made here https://github.com/megawac/generator-babel-node

### CODE REVIEW

**Comment by jmeas** [comment]
@megawac, feel free to turn this project into a yeoman generator.

**Comment by jmeas** [comment]
Haha, [awhile ago](https://github.com/jmeas/es6-node-boilerplate/issues/9)!

**Comment by thejameskyle** [comment]
Too late, I'm all about Ember CLI now :trollface:

**Pull request merged**
