### PR TITLE
Move configuration out of package.json.

### LINKED ISSUE #185: Remove config data from package.json
I originally put the boilerplate config in the package.json per @thejameskyle's suggestion. @megawac thinks it'd be better to put it in the gulpfile.

I'm fine either way, honestly. Any strong opinions here?

### PR DESCRIPTION
**Pull request by jmeas**
Resolves #185

===

Todo:

- [ ] Figure out how to support the browserify test setup in a DRY way.

### CODE REVIEW

**Comment by jmeas** [comment]
@megawac / @thejameskyle we may need to go back to a separate `config` file for this, so that I can reuse the same vars in [the browserify test setup file](https://github.com/babel/babel-library-boilerplate/blob/92f98c13acf472042e898f1b750ba36ef4daaac0/test/setup/browserify.js#L1).

**Comment by jmeas** [comment]
@megawac / @thejameskyle this is how [it used to be](https://github.com/babel/babel-library-boilerplate/blob/27839ab57ab708296f806ca2d952f4f92e4be83e/config/index.json), for reference. Do you prefer that over the package.json?

**Comment by thejameskyle** [comment]
Is there anyway you can pass the values to browserify/mocha without a separate file?

**Comment by jmeas** [comment]
I looked to see if mocha had a `mocharc` or something, but it doesn't seem to. The only other options I can think of atm are to either specify the mocha globals in two places, or create a specific file *just* for mocha globals.

**Comment by thejameskyle** [comment]
I mean you could also pass environment options with https://babeljs.io/docs/advanced/transformers/utility/inline-environment-variables/

**Comment by jmeas** [comment]
@thejameskyle, that is a nifty feature. I did some more research and found out about [mocha.opts](http://mochajs.org/#mocha-opts). I'm going to see if this and/or the feature you pointed out can be used to solve this problemo.

**Comment by jmeas** [comment]
Perhaps unsurprisingly, the browser build of the tests ignores the `mocha.opts` file. Yet the regular suite of tests doesn't seem to care about the globals at all, which is weird and might be a bug in and of itself.

**Comment by jmeas** [comment]
Gonna close for now; this will be super broken after yeoman lands.

**Pull request closed without merging**
