### PR TITLE
Add npm scripts to aid with releasing.

### LINKED ISSUE #179: preversion and prepublish
https://github.com/thejameskyle/a-damn-nice-test-repo/blob/master/package.json#L8-L9

```json
"scripts": {
  "preversion": "[[ -z $(git status --porcelain) ]] && npm run build && git add -A dist && git commit -m 'Build lib'",
  "prepublish": "git push origin master --follow-tags"
}
```

`npm version` will check for a clean repo, run the build, add the `dist` directory, commit the changes, and then run the rest of `npm version`.

`npm prepublish` will push the master branch and any tags to master before publishing on npm.

### PR DESCRIPTION
**Pull request by jmeas**
Resolves #179 

Todo:

- [x] Add docs

### CODE REVIEW

**Comment by jmeas** [comment]
@thejameskyle, [looks like Travis is trying to publish when it runs npm install...?](https://travis-ci.org/babel/babel-library-boilerplate/jobs/73396650#L93-L101)

**Comment by jmeas** [comment]
Oh, weird, `prepublish` is executed when you run `npm i` according [to the docs](https://docs.npmjs.com/misc/scripts).

**Comment by jmeas** [comment]
@thejameskyle, atm an `npm version` will create two commits: one for building the lib, and the other for bumping the version. The former is automatic, and the latter must be manually done. Should we use a `postversion` to group them *and* automate them?

**Comment by jmeas** [comment]
Oh, nvm, `-m` flag to `npm version`. Fancy.

**Comment by thejameskyle** [comment]
I think you also need to update your version of npm because they changed how it works

**Comment by jmeas** [comment]
Yeah, I can't get the `preversion` script to fire...I'll try upgrading...

**Comment by jmeas** [comment]
NICE. Updating `npm` worked. Thanks for the suggestion, @thejameskyle.

**Comment by megawac** [comment]
Do we really want to recommend scripts that are dependent on a certain npm revision?

**Comment by jmeas** [comment]
> Do we really want to recommend scripts that are dependent on a recent npm revision?

Probably not. I need to look at the changelog to see what's changed to make this work.

**Comment by thejameskyle** [comment]
> Do we really want to recommend scripts that are dependent on a recent npm revision?

@megawac don't you run the latest versions of everything all the time? \</sarcasm>

**Comment by jmeas** [comment]
I'm just gonna close this, cause the `preversion` script is substantially more useful than the `postpublish` one.

**Pull request closed without merging**
